USE videoclub;
DROP FUNCTION IF EXISTS act12;

DELIMITER //
CREATE FUNCTION act12(codiPeli SMALLINT UNSIGNED) 
	 RETURNS SMALLINT UNSIGNED
BEGIN

DECLARE nomActor VARCHAR(30);

SELECT PELLICULES.recaudacio_peli, PELLICULES.titol_peli, ACTORS.nom_actor, ACTORS_PELLICULES.principal
FROM PELLICULES
LEFT JOIN ACTORS_PELLICULES ON PELLICULES.id_peli = ACTORS_PELLICULES.id_peli 
LEFT JOIN ACTORS ON ACTORS_PELLICULES.id_actor = ACTORS.id_actor
WHERE ACTORS_PELLICULES.principal = 1;

RETURN nomActor;

END //
DELIMITER ;