USE videoclub;
DROP FUNCTION IF EXISTS act12;

DELIMITER //
CREATE FUNCTION act12(codiPeli SMALLINT UNSIGNED) 
	 RETURNS SMALLINT UNSIGNED
BEGIN

DECLARE nomActor VARCHAR(30);

SELECT ACTORS.id_actor, ACTORS.nom_actor, PELLICULES.id_peli, PELLICULES.titol_peli, ACTORS_PELLICULES.principal
INTO nomActor
FROM ACTORS
LEFT JOIN ACTORS_PELLICULES ON ACTORS.id_actor = ACTORS_PELLICULES.id_actor 
LEFT JOIN PELLICULES ON ACTORS_PELLICULES.id_peli = PELLICULES.id_peli
WHERE PELLICULES.id_peli = codiPeli AND ACTORS_PELLICULES.principal = 1;

RETURN nomActor;

END //
DELIMITER ;